;; This code was automatically generated by the 'metav' library.
(ns wallstreetbets-crawler.version)

(def module-name "wallstreetbets-crawler")
(def path ".")
(def version "0.1.0")
(def tag "v0.1.0")
(def generated-at "2022-07-10T21:08:46Z")
